### PR TITLE
Update the 30DCM-Website 

### PR DESCRIPTION
**Pull request by ambarja**
Hello @tjukanovt on this occasion I create a new pull-request for the integration of the [**repository**](https://github.com/hn303/30DayMapChallenge-Bot) files of @hn303 where you can find all the tweets that were published in the 30DCM, the best of all is that the files are markdown type.
source
I have also used the new @Namora logos. 
source02
Here, some screenshots and a quick video, If you want to add new content on the website, just edit the **mkdocs.yml** file (the whole website is based on markdown files and the deployment of the webpage is automatic thanks to GitHubActions).
gify
Finally, the url of the website is : https://tjukanovt.github.io/30DayMapChallenge, but you need to activate your GitHubPages, if you consider it I can help you, but you need to add as a collaborator to this repository. 
Here, the new structure of the repository :point_down: 
Presentation_01
Regards!

### CODE REVIEW

**Comment by lefcgis** [comment]
Done it!

**Comment by lefcgis** [comment]
Try to review this Peruvian technological alternativa, @tjukanovt 

As QGIS PERU core we are developed a local challenge some months ago. So we are invite you to review [our iniciative.](https://github.com/qgispe/30DayMapChallengeQGISPERU) ☺️✌🏼

Lucho 🥸

**Comment by ambarja** [comment]
Thanks @tjukanovt , please , is possible to active GithubPage and change the URL of the website in the description, the correct URL should be https://tjukanovt.github.io/30DayMapChallegue, I don't have permission in this part of the repository.

**Comment by tjukanovt** [comment]
@ambarja I modified the repo and the mkdocs.yml to use the 30daymapchallenge.com URL, but it doesn't quite look like in your video. What am I doing wrong? 😅

**Comment by ambarja** [comment]
@tjukanovt Here, are some steps to obtain a customised url :point_down: 
Presentation2_01

**Comment by lefcgis** [comment]
Thanks @ambarja to solve doubts and make efforts for @qgispe ! 🤠👓 #LivinOnAprayer 🎸

**Comment by tjukanovt** [comment]
Sorry @ambarja if I was unclear: I've already done the steps you mentioned and the site is live at https://30daymapchallenge.com/

However it doesn't have the sidebars etc. you had visible in your original PR and I wonder why?

**Comment by ambarja** [comment]
@tjukanovt maybe it is the custom url :cry: , but you can use the original url of the repository and share and see if the website is available, please edit also in the url of mkdocs, this in order to corroborate the website.

**Comment by tjukanovt** [comment]
@ambarja hmm.. it shouldn't be the custom domain as I changed the mkdocs.yml and added a CNAME to docs folder. But are you sure the page should be built from the root folder? Shouldn't it be the /docs folder? Here's what I have there now
image

...but the side panels don't seem to be working...

image

**Comment by ambarja** [comment]
@tjukanovt Please can you put in the branch gh-pages > root and then delete the 30daymapchallenge.com, finally save the changes and put the new url in the description, in theory it should come out.

**Comment by tjukanovt** [comment]
@ambarja Holy smokes! I got it working! Thank you for your help and patience. I will do a few small modifications today and will publish it to everyone!

Muchas gracias!

**Comment by ambarja** [comment]
@tjukanovt excellent, a note if you use ctrl +p, it generates a pdf of the main page as a broucher :) maybe it can be useful,regards!

**Pull request merged**
